name: Report
on:
  push:
    branches: [ main ]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "hello world" > ./data/index.html
          
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: data