name: Report
on:
  push:
    branches: [ main ]
jobs:
  sample:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[update report]')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm run report
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: data