name: Sample
on: [push]
jobs:
  sample:
    runs-on: ubuntu-latest
    env:
      IMPLEMENTATION: sample
      INPUT: /data/credentials/credential-0.json
      OUTPUT: /data/implementations/$IMPLEMENTATION/credential-0--key-0-p256.json
      KEY: /data/keys/key-0-p256.json
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose run $IMPLEMENTATION \
          credential verify \
          --input $INPUT \
          --output $OUTPUT
        