name: Sample
on:
  push:
    branches: [ main ]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Minimal Credential
      - run: |
          docker-compose run sample \
          credential create \
          --key /data/inputs/keys/private.ES256.json \
          --input /data/inputs/claimsets/_minimal-credential.json \
          --output /data/outputs/sample/_minimal-credential--private.ES256.json
      # Minimal Presentation
      - run: |
          docker-compose run sample \
          presentation create \
          --key /data/inputs/keys/private.ES256.json \
          --input /data/inputs/claimsets/_minimal-presentation.json \
          --output /data/outputs/sample/_minimal-presentation--private.ES256.json
      # Alumni Example
      - run: |
          docker-compose run sample \
          credential create \
          --key /data/inputs/keys/private.ES256.json \
          --input /data/inputs/claimsets/alumni-credential.json \
          --output /data/outputs/sample/alumni-credential--private.ES256.json
          
      - run: |
          ls -tlra /data/outputs/sample/*
