name: Sample
on: [push]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose run sample \
          credential create \
          --key inputs/keys/key-0-p256.json \
          --input inputs/credentials/credential-0.json \
          --output outputs/sample/credential-0--key-0-p256.json
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update sample test results
          file_pattern: 'outputs/sample/*'
          branch: main