name: Sample
on: [push]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose run sample \
          credential create \
          --input /data/credentials/credential-0.json \
          --output /data/implementations/sample/credential-0--key-0-p256.json \
          --key /data/keys/key-0-p256.json
        